### ISSUE TITLE
difference between the autoencoder and seq2seq

### ISSUE THREAD

**Issue by zhedongzheng** [JerrikEph/rnn_autoEncoder#1]
Hello, Dr Gong

Can I ask what is the difference between the rnn_autoencoder and the seq2seq model. From my perspective, when the inputs and outputs of a seq2seq model are both set to the same sentence / sequence, it acts like an autoencoder.

Are there some differences between the two things?
Thank you in advance for your time.

**Comment by jingjing-gong** [comment]
I think you have answered your own question, rnn_autoencoder is indeed an application of seq2seq model. I would think seq2seq model as a category of models that satisfies some characteristics instead of one specific model.
